spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Flyway configuration
  flyway:
    enabled: true                           # Enable Flyway (default: true)
    locations: classpath:db/migration       # Migration files location
    baseline-on-migrate: true               # Create schema_history if not exists
    validate-on-migrate: true               # Validate migrations before run

  jpa:
    hibernate:
      ddl-auto: validate                    # Let Flyway handle schema creation
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
