# Default config
spring:
  application:
    name: foodapp

  profiles:
    active: ${ENVIRONMENT:dev}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  file:
    name: ${LOG_PATH}/logging.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH:logs}/logging-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
      clean-history-on-start: false

app:
  upload:
    folder: /${UPLOAD_FOLDER}/
    location: ${APP_UPLOAD_LOCATION}/${UPLOAD_FOLDER}
  pagination:
    default-page: 1
    default-per-page: 5
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity: 7200000 # 2 hours (ms)
    refresh-token-validity: 604800000 # 7 days (ms)
